### ISSUE TITLE
Fix nested jinja

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/salesforce#3]
Nesting jinja is no longer allowed in dbt v0.15.0. Any instances of code like this:
https://github.com/fishtown-analytics/salesforce/blob/42f606016a87d9cb51003efafd8a26c7229fad31/models/transform/sf_opportunity_history_daily.sql#L36-L38

should be updated to not require double-interpolation

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
